export enum EnumIcons {
  audience = 'audience',
  dashboard = 'dashboard',
  devices = 'devices',
  metrics = 'metrics',
  offers = 'offers',
  pushes = 'pushes',
  arrow = 'arrow',
  calendar = 'calendar',
  choiceArrow = 'choiceArrow',
  close = 'close',
  info = 'info',
  plus = 'plus',
  trash = 'trash',
}
